version: "3.7"

networks:
  laravel:

volumes:
  database:

services:
  database:
    image: mysql:8.0.22
    restart: "no"
    volumes:
      - database:/var/lib/mysql
    networks:
      - laravel
    ports:
      - ${DOCKER_DATABASE_PORT}:${DB_PORT}
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    command: --default-authentication-plugin=mysql_native_password --local-infile

  app:
    restart: "no"
    volumes:
      - ./:/var/www
    environment:
      APP_ENV: ${APP_ENV}
    networks:
      - laravel
    build:
      context: .
      dockerfile: ./docker/dockerfile
    command: server

  webserver:
    image: nginx:stable
    restart: "no"
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    ports:
      - ${DOCKER_WEBSERVER_PORT}:80
    depends_on:
      - database
      - app
