#----------------------------------------
FROM composer:1.9.3 as composer
#----------------------------------------

WORKDIR /var/www
COPY . /var/www

RUN composer install --no-dev --ignore-platform-reqs --no-scripts

#----------------------------------------
FROM php:7.4.5-fpm-alpine AS production
#----------------------------------------

RUN apk update

RUN apk add --update nodejs npm python3 curl

RUN docker-php-ext-install pdo pdo_mysql mysqli

ENV PATH /opt/bin:$PATH

RUN apk add --no-cache \
    libzip-dev \
    zip \
    && docker-php-ext-install zip

RUN apk add gnu-libiconv --update-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted

ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so php

WORKDIR /var/www

COPY --from=composer /var/www /var/www
COPY docker/entrypoint.sh docker/entrypoint.sh

ENTRYPOINT [ "sh", "docker/entrypoint.sh" ]

CMD [ "server" ]
